apiVersion: v1
kind: ConfigMap
metadata:
  name: component-i4-0-cm
  namespace: default
data:

  # Properties files
  aas.properties: |
    logicalID=aas01
    endpoint=7000

    services.1=getAssetData
    services.2=getSubmodelData

  asset.properties: |
    assetType=physical
    assetID=KukaKR3
    assetNumber=1

  submodels.properties: |
    [technical-data-submodel]
    submodel1=technical-data
    submodel1.aas-id=11
    submodel1.aas-model=Kuka KR3

    [configuration-submodel]
    submodel2=configuration
    submodel2.aas-number=1
    submodel2.aas-level=edge